### ISSUE TITLE
files not updating due to git error?

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/extracted_sat_ts_gom_csv_data#3]
Attempting to manually run push file and getting the following error:

```
manglilloo:/srv/imars-objects/tpa_pgs/rois/gom/extracted_sat_ts_gom_csv_data> /bin/bash upload_files.sh 
============================================================
pulling repo to avoid merge conflicts...
fatal: update_ref failed for ref 'ORIG_HEAD': could not open '.git/ORIG_HEAD' for writing: File exists
```

A quick search didn't turn up any results for me on how to deal with this.

**Comment by dotis** [comment]
I have some new .csv files I have generated for met data from the buoy at Gray's Reef. Is there another place I should put them? Is there a gBucket available? Thanks.

**Comment by 7yl4r** [comment]
I have created a bucket that you may now be able to view in the google cloud console ([link that might work](https://console.cloud.google.com/storage/browser/dashboards_csvs;tab=objects?&project=mbon-early-alert-dashboards)).

We will need to use the `gsutil` tool from manglillo to do something like:

```
gsutil cp *.csv gs://dashboards_csvs
```

This is the same process I use for uploading the wv .tif files.

**Comment by dotis** [comment]
This seems to work, but it looks like I need to authenticate or be granted access. 

ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).

**Comment by 7yl4r** [comment]
set up on dotis@manglillo crontab completed
